# Generated by Django 5.2.5 on 2025-08-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformdata',
            name='ticket_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
