# Generated by Django 5.2.5 on 2025-08-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userformdata_ticket_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
