# Generated by Django 5.2.5 on 2025-08-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ticket_payment_screenshot_ticket_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPlaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='other_events/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
