# Generated by Django 5.2.5 on 2025-08-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_otherplaceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformdata',
            name='events',
            field=models.CharField(blank=True, help_text='Comma separated selected events', max_length=200),
        ),
    ]
