# Generated by Django 5.2.5 on 2025-08-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_contactmessage_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='participants/')),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('behance', models.URLField(blank=True)),
                ('dribbble', models.URLField(blank=True)),
                ('medium', models.URLField(blank=True)),
                ('kaggle', models.URLField(blank=True)),
            ],
        ),
    ]
