# Generated by Django 5.2.5 on 2025-08-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='behance',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='dribbble',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='github',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='kaggle',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='website',
        ),
    ]
