# Generated by Django 5.2.5 on 2025-08-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_participant_behance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherplaceevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='participants/'),
        ),
    ]
