# Generated by Django 5.2.5 on 2025-09-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_otherplaceevent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastevent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pastevent',
            name='description',
        ),
    ]
