# Generated by Django 5.2.5 on 2025-09-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_pastevent_date_remove_pastevent_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='role',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='skills',
        ),
        migrations.AddField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('Singing', 'Singing'), ('Dance', 'Dance'), ('Music Instrument', 'Music Instrument'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
