# Generated by Django 5.2.5 on 2025-09-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_participant_bio_remove_participant_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
