# Generated by Django 5.2.5 on 2025-09-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_participant_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.CharField(blank=True, choices=[('5-10', '5 Yrs to 10 Yrs'), ('11-20', '11 Yrs to 20 Yrs'), ('21-40', '21 Yrs to 40 Yrs'), ('41+', '41 Yrs and Above')], max_length=10, null=True),
        ),
    ]
