# Generated by Django 5.2.5 on 2025-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_participant_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherplaceevent',
            name='ticket_available',
            field=models.BooleanField(default=False, help_text='Set True if tickets are available for this event.'),
        ),
    ]
